### ISSUE TITLE
Some jupyter notebook are html

### ISSUE THREAD

**Issue by samuelemusiani** [cartabinaria/deep-learning#4]
@foxyseta ci sono due file che dovrebbero essere dei jupyter notebook ma sono degli html. Ho fatto velocemente un git blame e sembra li hai aggiunti tu qui 5a2009d8. Li ho provati ad aprire ma sinceramente non capisco il contenuto. Che ci facciamo?

I file sono:
```
exercises/lectures/00-mnist-dense.ipynb
exercises/lectures/01-my-first-nn.ipynb
```

**Comment by samuelemusiani** [comment]
Li ho scoperti perché la action per compilare i jupyter fallisce: https://github.com/csunibo/deep-learning/actions/runs/9480763018

**Comment by foxyseta** [comment]
Sono materiali provenienti da virtuale. Non ho idea del perché siano HTML dentro lo saprà il prof. Colpa mia che non ho controllato.

Tu hai seguito l'insegnamento nello scorso semestre, giusto? Quindi hai accesso a Virtuale e puoi o sostituirli con potenziali versioni corrette che sono presenti quest'anno o rimuoverli se non si riesce a salvare come cosa.

**Comment by samuelemusiani** [comment]
Deep learning è un corso della magistrale in AI, dire che non l'ho proprio fatto come corso :)

**Comment by foxyseta** [comment]
Ah ops hai ragione non intro all'apprendimento automatico. Allora non ricordo da dove provengano quei file e li cancellerei e basta(?).

**Comment by samuelemusiani** [comment]
Per me va bene cancellarli, faccio io
